.debian11-image: &debian11-image
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION

#################################################
# Makefile
#################################################

job-debian11-makefile-gcc:
  extends: .job-makefile-gcc
  <<: *debian11-image


job-debian11-makefile-clang:
  extends: .job-makefile-clang
  <<: *debian11-image

#################################################
# Ninja
#################################################

job-debian11-ninja-gcc:
  extends: .job-ninja-gcc
  <<: *debian11-image


job-debian11-ninja-clang:
  extends: .job-ninja-clang
  <<: *debian11-image
  variables:
    CMAKE_OPTIONS: -DENABLE_UNIT_TESTS=ON -DENABLE_UNIT_TESTS_MYSQL=ON
  artifacts:
    paths:
      - OUTPUT/*

#################################################
# XWiki reference documentation
#################################################

job-debian11-xwiki-doc-deploy:
  extends:
    - .rules-deploy  # âš  See `rules.yml`
  stage: build ðŸ—
  tags: [ "docker" ]
  <<: *debian11-image
  script:
    - prefix=/opt/belledonne-communications
    - builddir=build
    - sudo mkdir -p $prefix
    - sudo chown bc:bc $prefix
    - mkdir $builddir
    - cmake -S . -B $builddir -G Ninja -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_PREFIX_PATH=$prefix $DEFAULT_CMAKE_OPTIONS
    - cmake --build $builddir
    - /usr/bin/python3 ./doc/xw.py --flexisip-binary $builddir/src/flexisip -H $XWIKI_HOSTNAME -u $XWIKI_USERNAME -p $XWIKI_PASSWORD

#################################################
# DEB
#################################################

job-debian11-deb:
  tags: [ "docker" ]
  <<: *debian11-image
  extends: .job-linux-deb


job-debian11-deb-deploy:
  extends: .job-debian-deb-deploy
  variables:
    RELEASE: bullseye
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  dependencies:
    - job-debian11-deb


#################################################
# UNIT TESTS
#################################################

job-debian11-unit-test:
  extends: .unit-test
  <<: *debian11-image
  needs:
    - job-debian11-ninja-clang
